spring:
  application:
    name: service-pilotaircraft
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true # Para evitar problemas con nombres de host
        health-check-interval: 10s # Intervalo para verificar la salud del servicio
        register-health-check: true
      config:
        enabled: true
        format:
  datasource:
    url: jdbc:postgresql://localhost:5432/war_thunder_db
    username: war_thunder_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

pilotaircraft:
  services:
    pilots: http://localhost:8081/pilots
    aircrafts: http://localhost:8082/aircrafts

server:
  port: 8083