

GET localhost:8082/aircrafts/getAircrafts

###

GET localhost:8082/aircrafts/getAircraft/1

###

POST localhost:8082/aircrafts/saveAircraft
Content-Type: application/json

{
    "model": "F35 Lightning II",
    "registration": "CWQ-70",
    "manufacturer": "Lockheed Martin",
    "manufactured_year": 2024,
    "seats": 1,
    "flying_hours": 1
}
